### PR TITLE
Remove unused boundary generalized_tables

### PR DESCRIPTION
**Pull request by amatissart**
These tables are not used, as `boundary` layer reads "osm_**border**_linestring_genX" tables imported by osmborder.

### CODE REVIEW

**Comment by amatissart** [comment]
Actually `osm_boundary_linestring` table may be unused too ?

**Comment by jirik** [comment]
@amatissart Good point, thanks for this PR.

 > Actually osm_boundary_linestring table may be unused too ?

Exactly. Could you please add another commit to this PR deleting also `osm_boundary_linestring`, so that I can merge it together?

**Comment by amatissart** [comment]
I have made the requested change.  
You may want to update the diagrams upstream.

**Comment by jirik** [comment]
Thanks, I've also updated diagrams.

**Pull request merged**
