### PR TITLE
Add amenity=drinking_water

### LINKED ISSUE #569: No amenity=drinking_water in tiles
Hi,

Having `amenity=drinking_water` included in the tiles would be super useful and a good complement to `amenity=toilets` etc.

I can open a PR (with benchmarking) to add support for these.

Best,

### PR DESCRIPTION
**Pull request by kylebarron**
Fixes #569. 

I haven't tested this yet, but I think this is the only place that should need to be updated.

### CODE REVIEW

**Comment by zstadler** [comment]
@kylebarron 
Testing of this PR failed because some additional steps are required when a `mapping.yaml` file is modified.
Please read the section of [CONTRIBUTING.md](https://github.com/openmaptiles/openmaptiles/blob/master/CONTRIBUTING.md) that starts with
> When you modify import data rules in `mapping.yaml` or `*.sql`

**Comment by nyurik** [comment]
@kylebarron  please join us tomorrow at 10am US Eastern Time for the OpenMapTiles community sync up using https://meet.google.com/wsi-ebva-dhm . Not sure how to contact you directly - email me at YuriAstrakhan@gmail.com and I will add you to the proper invite in the future. Thanks!

**Comment by TomPohys** [comment]
Hi @kylebarron, can you please add missing changes (inspiration in https://github.com/openmaptiles/openmaptiles/pull/720)? Or we can close this PR and include drinking_water in subsequent bigger POI update?

**Comment by kylebarron** [comment]
I don't think I know what you mean by missing changes, and I don't see anything in #720 that explains it

**Comment by TomPohys** [comment]
Sorry for vague comment. 
In [CONTRIBUTING.md](https://github.com/openmaptiles/openmaptiles/blob/master/CONTRIBUTING.md) there are clear steps which have to be done when `mapping.yml` or `.sql` files are modified.

In Travis, there is an error 
```
docker-compose run --rm -u $(id -u ${USER}):$(id -g ${USER}) openmaptiles-tools generate-mapping-graph layers/poi/poi.yaml ./build/devdoc/mapping-diagram-poi
Binary files ./build/devdoc/mapping-diagram-poi.png and layers/poi/mapping_diagram.png differ
Makefile:205: recipe for target 'mapping-graph-poi' failed
make: *** [mapping-graph-poi] Error 2
```

There have to to be new `mapping_diagram.png` showing the new feature.

Before merging this type of PR (adding new features), you should also provide numbers which showing how much bigger the tiles are (the size of mbtiles for e.g. Switzerland grow by 10% form xxMB to XXMB)

**Comment by nyurik** [comment]
this PR failed because you had to run `make generate-devdoc` before submitting. I fixed it and pushed the update (together with the merge to the latest master). Will see the tilesize diff.

**Pull request merged**
