### PR TITLE
Remove support of relation type=street

### PR DESCRIPTION
**Pull request by frodrigo**
The member of relations `type=street` are imported.

There is 21 738 relations of this kind world wide. https://taginfo.openstreetmap.org/tags/type=street?filter=relations#overview

So, we import 986 076 objects as part of relation type=street relation. https://taginfo.openstreetmap.org/relations/street#overview

On this million objects, only 63 883 (6.4 %) match the request of the query (have a `house` role and are polygon) https://github.com/openmaptiles/openmaptiles/blob/master/layers/building/building.sql#L47

```
relation[type=street];
> ->.wr;
way.wr(r:"house")(if: is_closed()==1);
out count;
```

On this, only 433 does not already have a valid building tag, and so already imported into the building_polygon table.

```
relation[type=street];
> ->.wr;
(
  way.wr(r:"house")[building!~".*"](if: is_closed()==1);
  way.wr(r:"house")[building='no'](if: is_closed()==1);
);
out count;
```

Some are for sure false positive (`building:part` 67 (15 %), `landuse`: 63 (14 %), `barrier` 48 (11 %), `was:building`: 25 (6 %)). Total false positive: 203 (47 %).

```
relation[type=street];
> ->.wr;
(
  way.wr(r:"house")[building!~".*"]["building:part"](if: is_closed()==1);
  way.wr(r:"house")[building='no']["building:part"](if: is_closed()==1);
);
out count;
```

```
relation[type=street];
> ->.wr;
(
  way.wr(r:"house")[building!~".*"]["barrier"](if: is_closed()==1);
  way.wr(r:"house")[building='no']["barrier"](if: is_closed()==1);
);
out count;
```

```
relation[type=street];
> ->.wr;
(
  way.wr(r:"house")[building!~".*"]["landuse"](if: is_closed()==1);
  way.wr(r:"house")[building='no']["landuse"](if: is_closed()==1);
);
out count;
```

```
relation[type=street];
> ->.wr;
(
  way.wr(r:"house")[building!~".*"]["was:building"](if: is_closed()==1);
  way.wr(r:"house")[building='no']["was:building"](if: is_closed()==1);
);
out count;
```

Some others are possiblely false positive: `amenity` 164 (38 %)

```
relation[type=street];
> ->.wr;
(
  way.wr(r:"house")[building!~".*"]["amenity"](if: is_closed()==1);
  way.wr(r:"house")[building='no']["amenity"](if: is_closed()==1);
);
out count;
```

On the remaining less tagged objects (110), 45 are parts of multipolygon building relation and so already loaded in an other table.

```
relation[type=street];
> ->.wr;
(
  way.wr(r:"house")[building!~".*"]["amenity"!~".*"]["was:building"!~".*"]["building:part"!~".*"]["landuse"!~".*"]["barrier"!~".*"](if: is_closed()==1);
  way.wr(r:"house")[building='no']["amenity"!~".*"]["was:building"!~".*"]["building:part"!~".*"]["landuse"!~".*"]["barrier"!~".*"](if: is_closed()==1);
);
< ->.a;
relation.a[type=multipolygon][building];
out count;
```

So on one million objects initialy loaded, 65 objects maybe a tag less buildings.

Some of this objects are duplicate geometry of other buildings.

I conclude it not worth to loaded one million objects to rescue so few possibly mistaged buildings, while lot more objects are falsely load as buildings.

I suggest to remove the support of the `type=street` relations.

The relations associatedStreet have to be studied in the same way.

### CODE REVIEW

**Comment by frodrigo** [comment]
This PR and the following reduce z14 tiles time extraction in dense urban area by 25%.

**Comment by nyurik** [comment]
needs rebase

**Comment by frodrigo** [comment]
Rebased

**Comment by golubev** [comment]
Great research, @frodrigo! I am working on my custom buildings layer for my app. You have saved my time. Thanks!

**Comment by frodrigo** [comment]
> Why are you doing this? Ticket? - this is just code cleaning?

Data and code cleaning found in implementing #725

> How it will change the schema? - no change

No change

> How ti will affect the size of the output file? - no increase?

Lower, remove duplicate and bad data.

> How it will affect rendering time? - no increase?

Theoretically lower rendering time.

**Pull request merged**
