### PR TITLE
Add locksmith shop

### LINKED ISSUE #566: No locksmith shop on tiles
I report this issue : https://github.com/QwantResearch/qwantmaps/issues/23

It seems that there is no shoemaker or locksmith on openmaptiles : https://github.com/openmaptiles/openmaptiles/blob/master/layers/poi/mapping.yaml#L117

Could openmaptiles include the shop=locksmith tags ?

Thanks !

### PR DESCRIPTION
**Pull request by ZeLonewolf**
Fixes #566

This PR adds support for `shop=locksmith`.

Example OSM object: https://www.openstreetmap.org/way/874850561

Rendered tile:
image

### CODE REVIEW

**Comment by ZeLonewolf** [comment]
Note that #566 conflicts with #469.  We should really decide whether we want a white-list of shop values, or allow arbitrary values.

**Comment by farfromrefug** [comment]
@ZeLonewolf how do you decide which shops to show?
I mean i recently changed in my fork to show all shops except vacant and unknown. I feel it was too hard to decide which ones to show or not (for example sea_food is missing too)

**Comment by TomPohys** [comment]
Hi, thanks for the PR. Locksmiths are OK to add. I would like to not adding all shops with arbitrary values. There are a lot of names that are not useful at all. There is also big potential of vandalism with allowing `shop=*`

**Review by TomPohys — APPROVED** [review]

**Comment by farfromrefug** [comment]
@TomPohys good point! I was mostly asking how you choose which ones to show

**Comment by TomPohys** [comment]
@farfromrefug, if the shop's characteristics make sense (e.g. does not have like 10 records, or it is grey-zone ) to show, let's add it.

**Pull request merged**
