### PR TITLE
Housenumber and POI calc optimisation

### PR DESCRIPTION
**Pull request by edpop**
Hello.
This is for https://github.com/openmaptiles/openmaptiles/issues/209.
Please test the difference of speed in your real data and environment.

### CODE REVIEW

**Comment by stirringhalo** [comment]
Fantastic, comparing Albania before and after now!

**Comment by stirringhalo** [comment]
Fast-points method:

Housenumbers:
Time: 82.074 ms
CREATE SCHEMA
Time: 1.736 ms
CREATE TABLE
Time: 32.267 ms
CREATE FUNCTION
Time: 1.874 ms
CREATE FUNCTION
Time: 1.663 ms
CREATE TRIGGER
Time: 1.714 ms
CREATE TRIGGER
Time: 1.812 ms
CREATE FUNCTION
Time: 2.041 ms

POI:
Time: 409.666 ms
CREATE SCHEMA
Time: 1.728 ms
CREATE TABLE
Time: 22.672 ms
CREATE FUNCTION
Time: 1.733 ms
CREATE FUNCTION
Time: 1.673 ms
CREATE TRIGGER
Time: 1.587 ms
CREATE TRIGGER
Time: 1.769 ms
CREATE FUNCTION
Time: 1.950 ms
CREATE FUNCTION
Time: 2.074 ms
CREATE FUNCTION
Time: 1.941 ms

**Comment by stirringhalo** [comment]
Savings wasn't huge, but it was there, original method:

Housenumbers:
Time: 99.407 ms
CREATE SCHEMA
Time: 1.737 ms
CREATE TABLE
Time: 18.926 ms
CREATE FUNCTION
Time: 1.800 ms
CREATE FUNCTION
Time: 1.743 ms
CREATE TRIGGER
Time: 1.569 ms
CREATE TRIGGER
Time: 1.820 ms
CREATE FUNCTION
Time: 1.973 ms

POI:
Time: 505.183 ms
CREATE SCHEMA
Time: 1.768 ms
CREATE TABLE
Time: 22.652 ms
CREATE FUNCTION
Time: 1.899 ms
CREATE FUNCTION
Time: 1.748 ms
CREATE TRIGGER
Time: 1.774 ms
CREATE TRIGGER
Time: 1.937 ms
CREATE FUNCTION
Time: 1.960 ms
CREATE FUNCTION
Time: 2.213 ms
CREATE FUNCTION
Time: 2.001 ms

Perhaps my Albania import was just too small to accentuate the differences.  

Tiles.mbtiles for the old method and the new method were completely identical using the `sqldiff --table tiles` method. 

Then it dawned on me, you really should have it < 5 for the filter, otherwise you're not taking great advantage of the assumption. I am testing that change now.

**Comment by edpop** [comment]
You right, we should use ST_Cenetroid for triangular polygons too. The ST_NPoints returns 4 for them, because last point=start point.
```sql
SELECT ST_NPoints('POLYGON((75.15 29.53,77 29,77.6 29.5,75.15 29.53))'::geometry) --> 4
```
So we should use it for ST_NPoints < 6 (5 for quadrangular polygon).

**Comment by stirringhalo** [comment]
### Switzerland, latest method (< 5):
**Housenumbers:** 61896.608 ms
**POI:** 8295.065 ms

### Switzerland,  (= 5):
**Housenumbers:**  46291.249 ms
**POI:** 5988.861 ms

### Switzerland, original:
**Housenumbers:** 66212.247 ms
**POI:** 8158.724 ms
 Very interesting, the PointOnSurface function is probably pretty optimal for <= 4 points. If the assertion that 5 point polygons are always simple, then we do get the big benefit.

I want to try the following for a more generic case:

```
  SELECT CASE WHEN ST_Equals(ST_ConvexHull(the_geom),the_geom)
           THEN ST_Centroid(the_geom)
           ELSE ST_PointOnSurface(the_geom)
         END AS p
```
I'm not fond of the ST_NPoints(ST_ConvexHull(the_geom)) = ST_NPoints(the_geom) as although it isn't really wrong, it's not clear what the assumption is. Though we can use it if the cost of ST_Equals is too much.

**Comment by edpop** [comment]
I use `ST_NPoints(ST_ConvexHull(the_geom)) = ST_NPoints(the_geom)` as equivalent of missing `ST_IsConvex` function. It is much faster, than `ST_Equals(ST_ConvexHull(the_geom),the_geom)`, but much slower, that `ST_IsConvex` could be. I would very much like to add it to postgis somehow.

**Comment by stirringhalo** [comment]
Note, can't use ST_EQUALS, 

```
psql:/sql/tileset.sql:2256: ERROR:  Relate Operation called with a LWGEOMCOLLECTION type.  This is unsupported.
HINT:  Change argument 1: 'GEOMETRYCOLLECTION EMPTY'
CONTEXT:  SQL statement "UPDATE osm_housenumber_point
  SET geometry =
           CASE WHEN ST_Equals(ST_ConvexHull(geometry),geometry)
           THEN ST_Centroid(geometry)
           ELSE ST_PointOnSurface(geometry)
    END
  WHERE ST_GeometryType(geometry) <> 'ST_Point'"
PL/pgSQL function convert_housenumber_point() line 3 at SQL statement
```

**Comment by stirringhalo** [comment]
### Switzerland,  (NPoints = NPoints):
**Housenumbers:**  49845.841 ms
**POI:** 6099.805 ms

**Comment by stirringhalo** [comment]
I will be confirming in the next day or so that the results are identical to the original approach, then I will merge.

**Comment by stirringhalo** [comment]
Got matching results, squashing and merging.

**Pull request merged**
