### PR TITLE
Support docker compose V2 syntax `docker compose`

### PR DESCRIPTION
**Pull request by wcedmisten**
Currently the Makefile and `quickstart.sh` expect the [deprecated docker compose V1](https://docs.docker.com/compose/#compose-v2-and-the-new-docker-compose-command) syntax, `docker-compose`.
The new V2 syntax uses `docker compose` instead.

When using the V2 version, an error `docker-compose: command not found` occurs.

This is mentioned here: https://github.com/openmaptiles/openmaptiles/issues/1422 with suggestion to update the docs.

However, I think it would be preferable to support docker compose V2 syntax directly in the Makefile and `quickstart.sh`.

Let me know if you have any questions! I'm happy to explore a different approach to fixing this, I'm no make/bash expert, so if there's a better way, I'd be happy to adopt it.

### CODE REVIEW

**Comment by wcedmisten** [comment]
@TomPohys @ZeLonewolf do you all have any thoughts on this? Happy to create an Issue if discussion there is preferred.

**Comment by ZeLonewolf** [comment]
I'm a complete amateur around docker, so I don't have an opinion.  I would defer more to @nyurik.

**Comment by nyurik** [comment]
i don't see any reasons not to update to v2.  Overall, docker compose is a pain to use in many cases, and hard to scale it to use in k8s, but it does offer a quick start.

**Review by TomPohys — APPROVED** [review]

**Comment by TomPohys** [comment]
Thanks! It looks good!

**Pull request merged**
