### PR TITLE
Add bicycle, foot, horse, and mtb_scale to the transportation layer

### PR DESCRIPTION
**Pull request by zstadler**
Resolve https://github.com/openmaptiles/openmaptiles/issues/422
Resolve https://github.com/openmaptiles/openmaptiles/issues/512
Resolve https://github.com/openmaptiles/openmaptiles/issues/602

This is an extended and refined alternative to PR https://github.com/openmaptiles/openmaptiles/pull/573

### CODE REVIEW

**Comment by eva-j** [comment]
Thanks for this. However, maybe it would be better to make special fork for this topic. As already agreed here https://github.com/openmaptiles/openmaptiles/issues/572#issuecomment-473884057 and as mentioned in README.md, openmaptiles schema should stay simple for creating general basemaps.

**Comment by eva-j** [comment]
Please, could you solve conflicts and check difference in tile size (for Albania, Czech Republic, Switzerland)? We consider merging this in the end.

**Comment by zstadler** [comment]
@eva-j,
The conflicts have been resolved. 

The Albania tile size reported by Travis [for this branch](https://travis-ci.org/openmaptiles/openmaptiles/builds/603323321#L3043) is the same as the reported by Travis [for its base on the master branch](https://travis-ci.org/openmaptiles/openmaptiles/builds/602637785#L3035)

Unfortunately, I'm unable to check other difference in tile sizes as my master branch had already diverged from the origin.

**Comment by eva-j** [comment]
Thanks for resolving conflicts.

I generated mbtiles for Switzerland and Czechia without and with this addition, size increased this way:
```CH    262.1 MB (274 853 888) --> 263.1 MB (275 873 792)```
```CZ    521.5 MB (546 869 248) --> 522.4 MB (547 753 984)```

**Pull request merged**
