### PR TITLE
update the layers from natural earth latest data

### LINKED ISSUE #352: Layers refer to obsolete natural-earth relations
With latest natural-earth data (v4.0.0), some layers (such as "boundary") use sql tables that do not exist anymore.

For instance `ne_10m_admin_1_states_provinces_lines_shp` has been removed.
(see https://github.com/nvkelso/natural-earth-vector/blob/v4.0.0/CHANGELOG#L136)

This may be due simply to an unnecessary "_shp" suffix : https://github.com/nvkelso/natural-earth-vector/issues/123

### PR DESCRIPTION
**Pull request by antoine-de**
Natural earth has [released new data](http://www.naturalearthdata.com/updates/mail.cgi/archive/updates/20171103122417/) and now some sql query are invalid.

should fix #352

I don't really know how natural earth data versioning is maintained though :confused:

### CODE REVIEW

**Comment by antoine-de** [comment]
Note: the build fail because the image https://github.com/openmaptiles/import-natural-earth needs to be rebuild (and tagged) with the new data, but I can't do this

**Comment by nvkelso** [comment]
FYI: https://github.com/nvkelso/natural-earth-vector/#versioning

**Comment by jirik** [comment]
@antoine-de I have prepared version 1.4 (should be built in few minutes):
https://hub.docker.com/r/openmaptiles/import-natural-earth/builds/

Please update `import-natural-earth` to `1.4` in `docker-compose.yml` and push it to this PR.

**Comment by antoine-de** [comment]
donc @jirik , thanks

@nvkelso sorry I was not clear, I meant I didn't know the way openmaptiles handled the natural earth versioning (but I guess it's done via the docker tags)

**Comment by jirik** [comment]
@antoine-de Thanks for this PR, it's really helpful. Merged.

**Pull request merged**
