### PR TITLE
buildings: prevent slivers of self-intersecting geometry

### PR DESCRIPTION
**Pull request by quentar**
To address issue #1022 , where current New Zealand region with invalid data which aborts the import-sql loop.

It seems adding ST_IsValid condition to would pass and does not pass through New Zealand, however
flipping negative and positive radius for ST_Buffer helps to remove self-intersection.
It was suggested online at https://gis.stackexchange.com/questions/281935/topology-exception-on-geometry-intersection

Hopefully that should not have performance impact as it is not adding to the query.
Visually checking, regions buildings looks the same in output tiles, with benefit of New Zealand passing.

💡 At first I've tried adding ST_IsValid conditions at   https://github.com/openmaptiles/openmaptiles/blob/master/layers/building/update_building.sql#L27 
OR https://github.com/openmaptiles/openmaptiles/blob/master/layers/building/update_building.sql#L31
though it still aborted.

Issue log: (when doing `quickstart.sh new-zealand` , `make import-sql` step) 
<details>
CREATE FUNCTION
Time: 0.991 ms
psql:/sql/parallel/building.sql:82: ERROR:  lwgeom_union: GEOS Error: TopologyException: Input geom 0 is invalid: Self-intersection at or near point 19566767.608174294 -4873356.7422359968 at 19566767.608174294 -4873356.7422359968
CONTEXT:  PL/pgSQL function osm_building_block_gen1() line 6 at FOR over SELECT rows
Time: 150915.098 ms (02:30.915)
</details>

### CODE REVIEW

**Comment by TomPohys** [comment]
Hi @quentar, thanks for PR. If the visual check is OK, let's use it.

**Comment by TomPohys** [comment]
Hi @quentar, where did you test the buildings? 

The green buildings are original, red is your suggestion. Ideally, there should be just red buildings. A lot of buildings in zoom level 13 is now missing (pictures from Albania).

Screenshot from 2020-10-14 17-00-10

and detail with all building (zoom 14)
Screenshot from 2020-10-14 17-04-43

**Comment by quentar** [comment]
@TomPohys Thank you for testing that! I did not use this tool. I don't have many ideas what to try next though.

**Comment by fricna** [comment]
Was this issue resolved? I still encounter it when trying to process New Zealand and also Spain.

**Comment by TomPohys** [comment]
Let's close this PR in advance of https://github.com/openmaptiles/openmaptiles/pull/1044. 

New Zealand was fixed by ST_SnapToGrid function in [update_building.sql](https://github.com/openmaptiles/openmaptiles/pull/1044/files#diff-22d79c2879e2711c40bfdf951f23192854728687daa287c5dd8ec926372e57fcR44)

**Pull request closed without merging**
