### PR TITLE
Bench

### PR DESCRIPTION
**Pull request by cbeddow**
Bench is missing from amenities and not appearing on basemaps. I added it now in the same places were "drinking_water" appears as an amenity.

### CODE REVIEW

**Comment by frodrigo** [comment]
- You should not also submit packing in the same PR.
- You must update (generate) the doc on the PR.

I am in favour of adding bench. The SVG icon is already present.

**Comment by cbeddow** [comment]
@frodrigo thanks ,I fixed that extra commit on parking which is separate.

Are you saying to update the doc, I should run "make" with Docker, or something else? I don't understand which doc

**Comment by frodrigo** [comment]
> @frodrigo thanks ,I fixed that extra commit on parking which is separate.
> 
> Are you saying to update the doc, I should run "make" with Docker, or something else? I don't understand which doc

https://github.com/openmaptiles/openmaptiles/blob/master/CONTRIBUTING.md#code-review-process

**Comment by cbeddow** [comment]
@frodrigo do you know who I might ask about running this on Windows? I tried to run and just get tons of errors.

```
PS C:\omt\openmaptiles> make
/usr/bin/sh: line 0: .: .env: file not found
/usr/bin/sh: line 0: .: .env: file not found
/usr/bin/sh: line 0: .: .env: file not found
/usr/bin/sh: line 0: .: .env: file not found
/usr/bin/sh: line 0: .: .env: file not found
/usr/bin/sh: line 0: .: .env: file not found
/usr/bin/sh: line 0: .: .env: file not found
/usr/bin/sh: line 0: .: .env: file not found
/usr/bin/sh: line 0: .: .env: file not found
/usr/bin/sh: line 0: .: .env: file not found
/usr/bin/sh: line 0: .: .env: file not found
/usr/bin/sh: line 0: .: .env: file not found
/usr/bin/sh: line 0: .: .env: file not found
/usr/bin/sh: line 0: .: .env: file not found
/usr/bin/sh: line 0: .: .env: file not found
/usr/bin/sh: line 0: .: .env: file not found
/usr/bin/sh: line 0: .: .env: file not found
docker-compose run --rm --user=197612:197612 openmaptiles-tools bash -c \
                'generate-tm2source openmaptiles.yaml > build/openmaptiles.tm2source/data.yml'
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\utils\decorators.py", line 46, in inner
  File "site-packages\docker\api\client.py", line 228, in _get
  File "site-packages\requests\sessions.py", line 543, in get
  File "site-packages\requests\sessions.py", line 530, in request
  File "site-packages\requests\sessions.py", line 643, in send
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 677, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1244, in request
  File "http\client.py", line 1290, in _send_request
  File "http\client.py", line 1239, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 966, in send
  File "site-packages\docker\transport\npipeconn.py", line 32, in connect
  File "site-packages\docker\transport\npipesocket.py", line 23, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 72, in connect
  File "site-packages\docker\transport\npipesocket.py", line 59, in connect
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 123, in perform_command
  File "compose\cli\command.py", line 69, in project_from_options
  File "compose\cli\command.py", line 132, in get_project
  File "compose\cli\docker_client.py", line 43, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "site-packages\docker\api\client.py", line 188, in __init__
  File "site-packages\docker\api\client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
[14680] Failed to execute script docker-compose
make: *** [build/openmaptiles.tm2source/data.yml] Error -1
```

**Comment by TomPohys** [comment]
Hi, there is some discussion in [this issue](https://github.com/openmaptiles/openmaptiles/issues/1095), and my comment on how to install and use in [WSL2 ](https://github.com/openmaptiles/openmaptiles/issues/1095#issuecomment-817099375). 

I hope it will help.

**Comment by TomPohys** [comment]
Hi, do you have also some numbers, how much does it raises mbtiles on a bigger area (a state like France, or Germany)? (tests are using just some samples). Thanks

**Comment by cbeddow** [comment]
@TomPohys this adds 179,095 nodes to France, that are benches

**Comment by TomPohys** [comment]
Hi, even though there are "just" 2M benches (in comparison with 21M trees) benches should not be part of `POI` layer.

[amenity=bench](https://taginfo.openstreetmap.org/tags/amenity=bench) (e.g. https://www.openstreetmap.org/node/10701574772)

The benches (same as the trees) should not be part of the POI layer. The design of this schema is to be general-topographic. It would be better to add city-level and zoom 15 stuff (bench, trees) as a different layer with the behavior of https://github.com/openmaptiles/openmaptiles/pull/1003 turned off by default.

**Comment by TomPohys** [comment]
We can discuss the `amenity=bench` tag in a separate issue (open one if needed). Thanks!

**Pull request closed without merging**
