### PR TITLE
Add landuse=flowerbed to landcover

### LINKED ISSUE #1660: Add support for `landuse=flowerbed`
`landuse=flowerbed` is used to mark areas planted with decorative flowers. They're a common landscaping element, and useful to distinguish because they are generally not something to pass through (unlike grass), but should generally be shown as a green area to avoid gaps.

[Taginfo](https://taginfo.openstreetmap.org/tags/landuse=flowerbed#overview)
[Wiki](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dflowerbed)

Could this tag be added to the scheme?

### PR DESCRIPTION
**Pull request by nickswalker**
This adds `landuse=flowerbed` to landcover.

Closes #1660

### CODE REVIEW

**Comment by TomPohys** [comment]
Thanks for the PR! Could you please also add the `mapping.png` result from `make generate-devdoc`? 

Thanks :-)

**Comment by nickswalker** [comment]
Added!

**Comment by TomPohys** [comment]
Thanks! Sorry for prolonging this PR, but could you please extend the style to show the `flowerbed` ([readme about style](https://github.com/openmaptiles/openmaptiles/blob/master/style/README.md), [PR in OSM](https://github.com/gravitystorm/openstreetmap-carto/pull/4889))?

Thanks

**Comment by nickswalker** [comment]
I took a look but wasn't able to edit the style. Tileserver GL doesn't show the built style (#1663). I gather that the tileserver is supposed to serve the fonts and sprites as well, and that I won't be able to use local maputnik to display/edit the style without it.

**Comment by redheli** [comment]
try my PR, shall show the tyle
https://github.com/openmaptiles/openmaptiles/pull/1672

but if your style.json has format error, it is hard to debug with docker-compose

try run tileserver-gl inside docker, then you can see the console log
launch docker:
```
$ cd openmaptiles
$ docker run -it --rm --name tileserver-gl   -p ${TPORT:-8080}:${TPORT:-8080} --net=host  -v ./data:/data   -v ./style:/style   -v ./build:/build --entrypoint /bin/bash maptiler/tileserver-gl:lates
```

run tileserver-gl
```
$ /usr/src/app/docker-entrypoint.sh --port ${TPORT:-8080}  --config /style/config.json
```

**Comment by petraduriancikova** [comment]
@nickswalker You can reuse my code for the style changes. This adds the flowerbed pattern and polygon fill under it to the landcover layer.

The pattern image flowerbed_high_zoom.svg is from OSM, IMHO it's ok to use just the flowerbed_high_zoom, the mid_zoom is not so visible.

The changes need to be done on two layers: "landcover_subclasses" (adding the polygon fill with green color) and "landcover_subclass_patterns" (adding the flowerbed pattern).

Here you add the fill: https://github.com/openmaptiles/openmaptiles/blob/1ff51454518b8abbe03157ea5e23173a2496beb4/layers/landcover/style.json#L117C7-L189C11

`"flowerbed",
"#cdebb0"`

and then you add the "flowerbed" to filter: https://github.com/openmaptiles/openmaptiles/blob/1ff51454518b8abbe03157ea5e23173a2496beb4/layers/landcover/style.json#L192C7-L227C9

Here the pattern is added: https://github.com/openmaptiles/openmaptiles/blob/1ff51454518b8abbe03157ea5e23173a2496beb4/layers/landcover/style.json#L262C9-L307C10

`"flowerbed",
"flowerbed_high_zoom"`

And you add the "flowerbed" to the filter as well.

[style.json](https://github.com/user-attachments/files/16441807/style.json)
flowerbed_high_zoom

**Comment by nickswalker** [comment]
Thanks for the fixes and pointers! Flowerbeds render now.

image

**Comment by TomPohys** [comment]
Thanks a lot, both!

**Pull request merged**
