### PR TITLE
Add substantial missing languages

### PR DESCRIPTION
**Pull request by ZeLonewolf**
This PR adds eight missing languages, all of which are among the top 25 languages spoken in the United States, as discussed in ZeLonewolf/openstreetmap-americana#586, and have at least 10,000 `name:xx` usages in the database. Additionally, most of these languages are the primary or national language in the countries where they are most commonly spoken.

| Code    | Language            | Prevalence |
|---------|---------------------|------------|
| zh-Hant | Traditional Chinese | 129,822    |
| zh-Hans | Simplified Chinese  | 93,351     |
| ur      | Urdu                | 73,014     |
| fa      | Persian             | 49,495     |
| vi      | Vietnamese          | 28,238     |
| pa      | Punjabi             | 23,635     |
| pnb     | Western Punjabi     | 21,536     |
| bn      | Bengali             | 14,598     |

See also #1393

### CODE REVIEW

**Comment by claysmalley** [comment]
Here are some other languages with official status in at least one country and >10,000 instances of `name:xx` in OSM. Would it be out of scope to include these as well?

| Code | Language  | Prevalence |
|------|-----------|------------|
| `af` | Afrikaans | 16,497 |
| `kk` | Kazakh | 17,307 |
| `ks` | Kashmiri | 10,299 |
| `mr` | Marathi | 14,132 |
| `ms` | Malay | 20,947 |
| `my` | Burmese | 33,937 |
| `ne` | Nepali | 12,249 |
| `ps` | Pashto | 13,839 |

**Comment by TomPohys** [comment]
I generally agree, and there is no problem adding other languages that make sense (e.g. the official language of the country). But it's clear from the statistics that languages lift tile size significantly and we need to look at generalization and general reduction of tile size as well.

**Comment by nyurik** [comment]
@TomPohys are you sure languages increase the tile size that much?  Afterall, most different spellings of the same place are stored just once in a tile... I haven't done the stats though

**Comment by TomPohys** [comment]
I took the values from the tile statistics
 image

**Comment by nyurik** [comment]
right - so including more languages seem like growing by about 1-1.5%?  Seems fairly low?

**Comment by TomPohys** [comment]
Compared with e.g.
 - https://github.com/openmaptiles/openmaptiles/pull/1383 average tile size **+0.3%**
 - https://github.com/openmaptiles/openmaptiles/pull/1375 average tile size **+0.1%**
 - https://github.com/openmaptiles/openmaptiles/pull/1414 average tile size **+0.2%**
 - https://github.com/openmaptiles/openmaptiles/pull/1413 average tile size **+1.0%**

So adding languages will increase the size of the tiles quite a lot. I am not saying that these languages should not be added. Just an idea to look at some layers where some generalization or reduction could bring some decrease in tile size.

Please @claysmalley, create a new PR with your languages, to be more clear and distinguish between your PR (official languages in some countries) and this one (top 25 languages in the US). Thanks

**Review by TomPohys — APPROVED** [review]

**Pull request merged**
