### PR TITLE
Add "shop=car_parts" & "shop=e-cigarette"

### PR DESCRIPTION
**Pull request by jpbede**
This PR adds "shop=car_parts" and "shop=e-cigarette" POI's.
Do you need some tile size comparison ?

This PR refers to #469

### CODE REVIEW

**Comment by jpbede** [comment]
Tested on zoom level 12

| Country     | Before   | After    | Change  |
|-------------|----------|----------|---------|
| Switzerland | 41222144 | 41226240 | +0,01 % |

**Comment by TomPohys** [comment]
Hi @jpbede, Thanks for this PR. I have no problem with car_parts. On the other hand, e-cigarette shops are not so world-wide spread [(taginfo - 3k points)](https://taginfo.openstreetmap.org/tags/shop=e-cigarette) and it is for discussion if they should be in basemap.

**Comment by jpbede** [comment]
Sure, no problem. I thought that "e-cigarette" becomes more common. 
Unfortunately i've no evaluation of increase of new `shop=e-cigarette` POIs.

**Comment by TomPohys** [comment]
Hi @jpbede, could you please modify the PR and remove the e-cigarette? The cars_parts are OK. Thanks

**Comment by jpbede** [comment]
Done

**Comment by TomPohys** [comment]
Thanks @jpbede, approved.

**Pull request merged**
