### PR TITLE
Add `boundary=protected_area` parks

### PR DESCRIPTION
**Pull request by zstadler**
Update the **class** of the **park** layer in a backward-compatible way.

- The class for `boundary=protected_area` parks is the lower-case of the [`protection_title`](http://wiki.openstreetmap.org/wiki/key:protection_title) value, with blanks replaced by `_`.
- `national_park` is the class of `protection_title=National Park` and `boundary=national_park` parks.
- `nature_reserve` is the class of `protection_title=Nature Reserve` and `leisure=nature_reserve` parks.
- The class for parks with other [`protection_title`](http://wiki.openstreetmap.org/wiki/key:protection_title) values is similarly assigned.

Resolve https://github.com/openmaptiles/openmaptiles/issues/760

### CODE REVIEW

**Comment by nyurik** [comment]
@zstadler please join us tomorrow at 10am US Eastern Time for the OpenMapTiles community sync up using https://meet.google.com/wsi-ebva-dhm . Not sure how to contact you directly - email me at YuriAstrakhan@gmail.com and I will add you to the proper invite in the future. Thanks!

**Comment by zstadler** [comment]
This PR may also resolve https://github.com/openmaptiles/openmaptiles/issues/542

**Comment by zstadler** [comment]
Will also resolve https://github.com/openmaptiles/openmaptiles/issues/542

**Comment by TomPohys** [comment]
Hi @zstadler 

There is **no impact** on performance! 

Tested on Czech Republic:

- just park layer
        - original - 6.4MB
        - with protected areas - 9.9MB (+35.35%)
- whole Czech Republic
       - original - 554MB
       - with protected areas - 556.4MB (**0.43%**)

cr_original
cr_protected_areas

Original             |  Extended
:-------------------------:|:-------------------------:
733_original  |  773_extended

**Pull request merged**
