### PR TITLE
Quickstart refactoring   #261

### PR DESCRIPTION
**Pull request by ImreSamu**
First part of #261

quick refactoring
*  Moving 'osm2vectortiles/mapbox-studio ' definitions from the docker-compose.yml to the Makefile, 
   *   this part is needs more testing!   if the users complaining - we need to restore this part.
*  `nohup quickstart.sh`   support #166
*  removing current quickstart warnings.  ( quick fix )
```
The MIN_ZOOM variable is not set. Defaulting to a blank string.
The MAX_ZOOM variable is not set. Defaulting to a blank string.
```
*  add `generate-devdoc` to travis check  ( maybe this is help to detect warnings! ) 

example: 
```
docker-compose run -T --rm openmaptiles-tools generate-etlgraph layers/landcover/landcover.yaml						./build/devdoc
Warning: node layer_landcover, port z5_6 unrecognized
Warning: node layer_landcover, port z7 unrecognized
Warning: node layer_landcover, port z5_6 unrecognized
Warning: node layer_landcover, port z7 unrecognized
```

### CODE REVIEW

**Comment by jirik** [comment]
@ImreSamu Will you continue with this PR? It states "First part of #261", so I expected that you will extend it, but nothing happens in last 6 months.

**Comment by ImreSamu** [comment]
>Will you continue with this PR?
Probably I have not enough capacity in the next month, so you can adapt, continue, close  - as you like,  
sorry,

**Comment by jirik** [comment]
Thanks for reply, I will try to look at it prior to 3.8.

**Comment by klokan** [comment]
This is very old work - not touched by anybody for almost two years. Closing.

**Comment by nyurik** [comment]
Agree, and besides, we should probably upgrade to the newest tools first before doing any quickstart cleanup.

**Pull request closed without merging**
