### PR TITLE
show tracks / paths at zoom 12 and 13

### PR DESCRIPTION
**Pull request by farfromrefug**
As discussed this PR changed the visibility of tracks/paths to be shown at lower level as done by most hikings maps

### CODE REVIEW

**Comment by nyurik** [comment]
@farfromrefug please update the first comment, describing what you are trying to do

**Comment by ZeLonewolf** [comment]
I believe the intent is for this to fix #271

**Comment by farfromrefug** [comment]
Btw i have to say i am not 100% sure this would go in the main repo. Feels weird to me to have tracks/paths showing before minor for non hiking maps. It.might a first step befote having configurable min zoom level

**Comment by TomPohys** [comment]
Hi, thanks for PR. based on github-actions statistics, there is a raise in tile size by 28% and 19% for zoom 11 and 12. Could you please provide statistics how much will raise the whole mbtiles for some bigger areas (France, Switzerland or Europe)? Thanks

**Comment by ZeLonewolf** [comment]
I was surprised to see how big the tile increase was - more than I expected.  I think the goal here is really to show hiking trails at lower zooms, but not specifically all paths.

If you look at the tag conflation of `highway=path`, [it's quite telling](https://taginfo.openstreetmap.org/tags/highway=path#combinations): 
* Only 5.2% of paths have a `name=*` tag
* Only 4.7% of paths have a `sac_scale=*` tag

Instead, I think it would make more sense at these zooms to only show the paths that have some type of tagging that indicates that they're a hiking trail.  This would eliminate 90%+ of paths added in the PR but would still leave behind paths that are important to show at lower zooms.

**Comment by farfromrefug** [comment]
Interesting point. Now from an hiking app point of view you need them all. Let me explain. 
In my app style, i, by mistake, did exactly what you suggested. I had all data from zoom 12 but filtered on sacscale until zoom 13.
As you can see in the screenshots (zoom at bottom right) the most important paths (those leading to summits) dont have sac scale and thus are filtered until zoom 13. Thus showing only sacscale from zoom 12 is kind of useless. 
The more i think about it the less i think this should be in master
Screenshot_20210824-083945_Alpi_Maps
Screenshot_20210824-083941_Alpi_Maps

**Comment by ZeLonewolf** [comment]
@farfromrefug I think "only `sac_scale`" is not enough, as you note.  However, any trail with a `name`, `sac_scale`, is part of a route relation, has a `colour`, `osmc:symbol`... and possibly other checks we can make, is probably a hiking trail, and that filter would STILL eliminate probably 90%+ of the path objects while still leaving behind the paths that make sense to show.

**Comment by farfromrefug** [comment]
@ZeLonewolf at least not in France. Most deep montain trails are only path/path. From what i am seeing ( and it is sometimes tough to style) it is far from 90% of true hiking trails. A funny test would be to see what the closest paths from peaks are tagged. surely for like the Mont Blanc they have tags. But from what i see in the french Alps it is not the case

**Comment by ZeLonewolf** [comment]
Surely there is some middle ground that can be achieved between "all paths at z12-13" and "no paths at z12-13" so that general purpose styles can still show some trails at these zooms.

**Comment by farfromrefug** [comment]
@ZeLonewolf my point is if we  want to add path at zoom 12 because of hiking apps it seems to me it should either b all or none. as an hiking app devs the middle ground is kind of useless. And it does rise tile s size for everyone not only hiking apps devs. 
Just my opinion, personally dont really care as i use my own fork...

**Comment by ZeLonewolf** [comment]
I think we want to add (important) paths up to zoom 12 because it's of general interest to general-purpose maps, not just hiking maps.  This exposes yet again the need to have switchable customizations so that every minor adjustment doesn't require a fork of the SQL layer.

**Comment by TomPohys** [comment]
Thank you for the discussion. Let's close this in advance of #1190, where @ZeLonewolf using path filtering for z12 and z13.

**Pull request closed without merging**
