### PR TITLE
Update naming convention for networks

### PR DESCRIPTION
**Pull request by remyleone**
Update naming convention for networks with the goal to make it easier to use with kompose

### CODE REVIEW

**Comment by nyurik** [comment]
Would it make sense to get rid of the dash/underscore completely, e.g. use `postgres` or even `pg` network name?  Simpler is usually better :)

**Comment by remyleone** [comment]
Let's go for `postgres` then :)

**Review by TomPohys — APPROVED** [review]

**Comment by TomPohys** [comment]
Thanks @remyleone

**Comment by frodrigo** [comment]
Should also be fixed here?
- https://github.com/openmaptiles/openmaptiles-tools/blob/master/tests/sql/docker-compose.yml
- https://github.com/openmaptiles/openmaptiles-tools/blob/master/README.md

**Comment by nyurik** [comment]
> Should also be fixed here?
> 
> * https://github.com/openmaptiles/openmaptiles-tools/blob/master/tests/sql/docker-compose.yml
> * https://github.com/openmaptiles/openmaptiles-tools/blob/master/README.md

good catch @frodrigo , want to submit a PR?  I will try to get to it tomorrow

**Comment by remyleone** [comment]
I can do it :)

**Pull request merged**
