### PR TITLE
Adding volcanoes

### PR DESCRIPTION
**Pull request by eva-j**
- https://github.com/openmaptiles/openmaptiles/issues/420
- "natural" added to osm_peak_point - loading now 'peak' and 'volcano'
- edit mountain_peak layer in Topo style and add mountain_volcano layer; layers should then look like
[styl_mountain_peak_volcano.txt](https://github.com/openmaptiles/openmaptiles/files/3039347/styl_mountain_peak_volcano.txt)

### CODE REVIEW

**Comment by typebrook** [comment]
Duplicate to #553, the difference is about name of new field in `mountain_peak` layer: `class`(my PR) and `natural`(This one).

**Comment by eva-j** [comment]
You are right, we can now decide witch version we want to merge. Was there any reason for renaming field `natural` to `class`? I would prefer to keep consistency with OSM tagging and approach in other layers - it is used e.g. in water, landcover.

**Comment by typebrook** [comment]
As my opinion, the use case of this layer should be includes markable natural landscape that user can recognize them from a long distance.

> Was there any reason for renaming field `natural` to `class`?

Because I am thinking maybe we need to include some man-made OSM features into this layer in the future, to show natural landscape which is not in OSM but markable. In this case, `class` would be a general field to use.

Some countries like Taiwan or Japan have `man_made=survey_point` for topography use case on unnamed peaks. For example [node 5696179414](https://www.openstreetmap.org/node/5696179414) only tagged as `man_made=survey_point` but in Google Map it is shown as mountain peak called [奥聖岳](https://goo.gl/maps/gRDMmskihSA2)

And according to [Mapbox Street v7](https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v7/#mountain_peak_label), it is reasonable to includes `hilltop` inside this layer. So maybe things like `power lines` or `radio tower` on the top would be the better choice to be included.

Of course things above need to have some discussion before being part of OpenMapTiles schema, but I just think a general field name would be a better choice.

**Comment by eva-j** [comment]
OK, this makes sense, I am closing this.

**Pull request closed without merging**
