### PR TITLE
Adding source_ids column if not exists.

### PR DESCRIPTION
**Pull request by TomPohys**
Fix https://github.com/openmaptiles/openmaptiles/issues/1556

Adding source_ids column if not exist in the table 
 - osm_transportation_merge_linestring_gen_z11
 - osm_transportation_merge_linestring_gen_z8
 - osm_transportation_name_linestring
 - osm_important_waterway_linestring

Dropped source_ids causing an error for the second run of `import-sql`.

[Diff test](https://github.com/openmaptiles/openmaptiles/blob/master/CONTRIBUTING.md#verifying-that-updates-still-work) and [integration test](https://github.com/openmaptiles/openmaptiles/blob/master/TESTING.md#openmaptiles-sql-testing) pass

cc: @benedikt-brandtner-bikemap

### CODE REVIEW

**Comment by benedikt-brandtner-bikemap** [comment]
Sorry was a bit busy, thanks a lot will have a look a little later today

**Comment by ZeLonewolf** [comment]
I also encountered this error, thanks for posting a fix!

**Comment by benedikt-brandtner-bikemap** [comment]
sorry for taking so long again this looks good to me!
it seems like i never reused an already existing database so i never encountered this error during development :/

thanks for the fix!

**Comment by TomPohys** [comment]
Thanks for look on it!

**Pull request merged**
