### PR TITLE
Update makefile to catch WSL folder error

### LINKED ISSUE #1103: Update makefile to catch WSL folder error
This continues from https://github.com/openmaptiles/openmaptiles/issues/1095#issuecomment-819679870

Windows Subsystem for Linux not read correctly `*.bbox` file and raise an error.

How to update Makefile to catch this error?

### PR DESCRIPTION
**Pull request by zstadler**
- Resolve #1103
- Remove dead code

### CODE REVIEW

**Comment by TomPohys** [comment]
Thanks for PR. But it somehow creating folders (`build`, `cache` and `data`) as a `root` user. Is it something to do with `shell` before `docker-compose`?

The `--rm` should not be replaced by a `$(DC_OPTS)`? 

Thanks

**Comment by zstadler** [comment]
Apparently, if the `data`, `build`, and `cache` are created by `docker-compose`, they have `root` ownership regardless of the `docker-compose --user` parameter:

```
$ sudo rm -fr data cache build
$ docker-compose run --rm --user=1000:1000 openmaptiles-tools df --output=fstype /tileset
Creating patch-1103_openmaptiles-tools_run ... done
Type
ext4
$ ls -dl data cache build
drwxr-xr-x 3 root root 4096 Apr 26 17:41 build
drwxr-xr-x 2 root root 4096 Apr 26 17:41 cache
drwxr-xr-x 2 root root 4096 Apr 26 17:41 data
```

**Comment by zstadler** [comment]
@TomPohys , I have no idea why the Evaluate performance check failed. Could you please look at it?

**Comment by TomPohys** [comment]
Thanks, it looks good.

**Review by TomPohys — APPROVED** [review]

**Pull request merged**
