### PR TITLE
Daily updates

### PR DESCRIPTION
**Pull request by stirringhalo**
This PR enables daily updates when omniscale/imposm3 is used. Right now it doesn't reflect the syntax of https://github.com/openmaptiles/openmaptiles/pull/124 but this PR should not impact current use of OpenMapTiles with our fork of Imposm3.

Once this is merged, I will look into faster refresh (https://github.com/openmaptiles/openmaptiles/issues/129) where it may be possible to get down to hourly with parallel SQL updates.

### CODE REVIEW

**Comment by stirringhalo** [comment]
It took about 11 hours to do a daily update, most of which was spent refreshing transportation_names layer.

**Comment by ImreSamu** [comment]
@stirringhalo :   Probably I can test at the weekend, not early ..   sorry

**Comment by lukasmartinelli** [comment]
This has been a huge effort from what I see. Respect :clap: 

To generalize:

1. This recreates a trigger each time at insert time
2. Then it creates the derived tables/runs the updates
3. This trigger is bound to each modification of the derived table (INSERT/UPDATE/DELETE) but only executed after each commit?
4. The trigger then refreshes the table when imposm3 imports

So after these PR's we can guarantee the following for derived tables

1. Each time we run `import-sql` the derived tables get created (but only the first time right?)
2. Each time we run import the derived tables now get automatically updated :+1: 

Did I understand this correctly?

**Comment by stirringhalo** [comment]
I should've described how this work!

> To generalize:
>
> 1.    This recreates a trigger each time at insert time
> 2.    Then it creates the derived tables/runs the updates
> 3.    This trigger is bound to each modification of the derived table (INSERT/UPDATE/DELETE) but only executed after each commit?
> 4.    The trigger then refreshes the table when imposm3 imports
>
> So after these PR's we can guarantee the following for derived tables
>
> 1.   Each time we run import-sql the derived tables get created (but only the first time right?)
> 2.   Each time we run import the derived tables now get automatically updated :+1:
>
> Did I understand this correctly?

What you do is run the import-osm, import-sql sequence as normal.

import-sql creates the triggers, flag and update functions as well as the triggers.

Afterwards, you run the update-osm which you have in the  compose_update branch. That runs continuously.

On each INSERT/UPDATE/DELETE, the .flag() function gets executed, which UPSERTs into the .updates table when an update is needed. Only one row gets inserted into .updates per commit.

The .update() function is deferred, which means it gets executed at the end. For each row of of the .updates table, which is just one flag row, the .refresh() function gets executed, which is either a MATERIALIZED VIEW refresh or an UPDATE depending on the layer.  

Every .refresh() raises a notice describing which layer is being refreshed.

You mentioned in one comment a pile of errors for `imposm3 run`? I've had a few, but I have a long running update that I can check on. I use `docker logs` so I can peer back into the logs.

**Comment by stirringhalo** [comment]
Wohoo!

**Pull request merged**
