### PR TITLE
Update makefile for hierarchical area names

### PR DESCRIPTION
**Pull request by zstadler**
- Use `find` instead of `wildcard` to detect existing `.osm.pbf` files
- Use `patsubst` to extract an `area` from a filename
- Clarify messssage, especially for errors

Resolve https://github.com/openmaptiles/openmaptiles/issues/1008

### CODE REVIEW

**Comment by zstadler** [comment]
@nyurik,
Could you review and approve this PR?
It is important for using osmfr

**Review by nyurik — APPROVED** [review]
i'm fine with this, but one issue others may have is that this makes the script linux/macOS only, whereas before it was "kinda" able to run on Windows too (at least that's what I heard).

**Comment by zstadler** [comment]
I've tested this PR on both Windows and Linux. 

AFAIK, the OMT project requires a `bash` shell, such as Docker Toolbox, in order to run on Windows.
The ability to run Linux/MacOS commands is already assumed by the `Makefile` in several places, including
```
DC_OPTS ?= --rm --user=$(shell id -u):$(shell id -g)
```
A `bash` shell is also needed in order to run `quickstart.sh`.

**Review by TomPohys — APPROVED** [review]

**Comment by TomPohys** [comment]
Thanks @zstadler.

**Comment by zstadler** [comment]
Thanks @nyurik and @TomPohys!

**Pull request merged**
