### PR TITLE
Stitch `transportation_name` by all language tags

### PR DESCRIPTION
**Pull request by zstadler**
When OSM roads in the `transportation_name` layer are stitched together, their grouping does not consider all `name:*` tags.
As a result, roads with different `name:*` tags may be stitched together.

The `waterway` layer performs the grouping properly, for the same purpose:
https://github.com/openmaptiles/openmaptiles/blob/1685eaccbd0ab9f8e4b32bcd4f4a20fd502a5d13/layers/waterway/update_important_waterway.sql#L34

### CODE REVIEW

**Comment by zstadler** [comment]
@frodrigo and @TomPohys,
PR #991 and this PR are independent in functionality yet their merge is non-trivial.
Will it be OK with you to merge #991 first, let me resolve the conflicts, and then merge this PR?

**Comment by TomPohys** [comment]
Hi @zstadler, thanks for this PR. Of course, the #991 is merged. 

Do you think, that it can resolve https://github.com/openmaptiles/openmaptiles/issues/762?

**Comment by zstadler** [comment]
> Do you think, that it can resolve #762?

Most probably, yes.

As far as I understood [the comment by @eva-j](https://github.com/openmaptiles/openmaptiles/issues/762#issuecomment-635572387), the root cause of that issue is a merge of highways with incompatible `tags` values. In this PR the grouping is done only between identical `tag` values.

```diff
-         GROUP BY name, name_en, name_de, ref, highway, construction, "level", layer, indoor, network_type
+         GROUP BY name, name_en, name_de, tags, ref, highway, construction, "level", layer, indoor, network_type
```

**Comment by zstadler** [comment]
@TomPohys, the merge with `master` is done.

**Comment by TomPohys** [comment]
Thanks a lot, @zstadler.

**Pull request merged**
