### PR TITLE
Add leisure=swimming_pool as water

### PR DESCRIPTION
**Pull request by jpbede**
Adds tag `leisure=swimming_pool` as water polygon

### CODE REVIEW

**Comment by TomPohys** [comment]
Hi @jpbede, thank you for this PR. It is very useful, but we need to know the exact increase in data volume of resulted mbtiles file. Could you please test this PR on one whole country, e.g. Switzerland, the Czech Republic or your country?

Thanks

**Comment by jpbede** [comment]
Sure, no problem :)

**Comment by jpbede** [comment]
Tested on zoom level 12

| Country     | Before   | After    | Change  |
|-------------|----------|----------|---------|
| Switzerland | 41222144 | 41246720 | +0,06 % |

**Comment by nyurik** [comment]
@TomPohys I think github action creates very accurate numbers for the SIZE changes, but not for SPEED changes.

**Comment by jpbede** [comment]
I could also create a comparison of time, if you wish ?

**Comment by nyurik** [comment]
I'm not sure if its worth it for such a tiny change

**Comment by TomPohys** [comment]
@jpbede thank you for the test and this PR.

**Pull request merged**
