### PR TITLE
Add place=quarter to city subdivisions

### PR DESCRIPTION
**Pull request by jdhoek**
This adds `place=quarter` which was introduced in 2011 as a subdivision
of villages/towns/cities as a value that sits between `place=suburb` and
`place=neighbourhood`. It has by now been used over 40,000 times and is
rendered in the OSM-Carto.

Might solve #1064.

### CODE REVIEW

**Comment by jdhoek** [comment]
This is just a very naïve commit that puts `place=quarter` in between anywhere `place=suburb` and `place=neighbourhood` are used. I don't know if this is sufficient, or if this brakes things.

**Comment by jdhoek** [comment]
In terms of ordering this is correct of course, all three are urban subdivisions, starting from the largest: `suburb`, `quarter`, `neighbourhood`. So where the other two are used `quarter` sits between them.

**Comment by TomPohys** [comment]
Thank you for PR. Could you please update a devdoc by `make generate-devdoc` to update diagrams? Thanks

**Comment by jdhoek** [comment]
Done. Two files changed, looks good:

mapping_diagram

mapping_diagram

**Review by TomPohys — APPROVED** [review]

**Pull request merged**
