### PR TITLE
Support trees from natural=tree #405

### PR DESCRIPTION
**Pull request by frodrigo**
Add support of natural=tree, without any specific tags.

**NOTE: I do not include the mapping_diagram.png, how to get it ?**

image

### CODE REVIEW

**Comment by daliborjanak** [comment]
Thanks for PR. It does not make sense to add it as a new layer. It is not often used thing and not especially used in base maps. It is a candidate for special external layer.

**Comment by frodrigo** [comment]
What are external layer ? some kind of contrib layer ?

**Comment by typebrook** [comment]
> What are external layer ? some kind of contrib layer ?

@frodrigo 
Means a vector tiles source **not in openmaptiles**. Consider tile size, we should only include layers for **general user cases**. Of course we still can make other layers in additional tile source.

For example, see [contour](https://github.com/openmaptiles/klokantech-terrain-gl-style/blob/014d553f2d7358c921a897590e43b04cfe4745eb/style.json#L29-L31) used in `klokantech-terrain-gl-style`

**Comment by eva-j** [comment]
Please create fork for this topic, if you want. We can't merge this into general OMT schema, because the tile size would increase a lot and not many people would use it...

**Comment by cbeddow** [comment]
Made a pull request here, but it may need some extra specification of the styling because an icon does not exist

https://github.com/openmaptiles/openmaptiles/pull/1545

**Pull request closed without merging**
