### PR TITLE
[WIP] imposm3 mapping change to the new reject/require syntax

### PR DESCRIPTION
**Pull request by ImreSamu**
Work in progress ..
- [x] rewrite to the new imposm3 filter syntax  ..
- [x] testing   -   with a  `import-osm:01` :   same record number    :  OK  
- [ ] testing ....

works with:  https://github.com/openmaptiles/import-osm/pull/6

### CODE REVIEW

**Comment by ImreSamu** [comment]
@lukasmartinelli ,
first tests ok ...  ,  
*  if you want merge - it is works with https://github.com/openmaptiles/import-osm/pull/6

**Comment by lukasmartinelli** [comment]
Can we remove the commented out code and switch to `import-osm:0.3` (which will contain openmaptiles/import-osm#6) and then merge?

**Comment by ImreSamu** [comment]
@lukasmartinelli  :    yes ..  :+1:

**Comment by ImreSamu** [comment]
> removing - commented out code 

I can to do  at night ,  but no problem if you do ..

**Pull request merged**
