### PR TITLE
Make update_osm_peak_point use incremental update #814

### PR DESCRIPTION
**Pull request by frodrigo**
Replacing update on the whole table with an update only on changed rows.

The goal is to update more quickly by just updating the changing content.
The update now focus on `osm_id` of changed rows, it use index. Add a where clause `tags != update_tags(tags, geometry)` en ensure only update when changed.

It now requires only one trigger in place of two.

The `UPDATE` is keep in a function to be reutilisable for initial setup and trigger update, the switch is done with `(new_osm_id IS NULL OR osm_id = new_osm_id)`.

It is a prof of concept. If it is ok, I will do batch of these on other similar updates.

It addresses #814.

Note: `update_tags` is already IMMUTABLE but can be switched to pure SQL and parallel safe https://github.com/openmaptiles/openmaptiles-tools/blob/master/sql/zzz_language.sql#L154

### CODE REVIEW

**Comment by nyurik** [comment]
I propose we solve #899 first -- this way we can test if these types of changes are ok to merge automatically.  Anyone wants to tackle that?

**Comment by nyurik** [comment]
@frodrigo hi, i merged the conflict with your patch, but please double check the logic

**Comment by frodrigo** [comment]
Thank, I will make the similar others when I will have more free time. Probably in July.

**Comment by TomPohys** [comment]
Awesome, thanks.

**Pull request merged**
