### PR TITLE
Update Performance transportation_name Layer

### PR DESCRIPTION
**Pull request by benedikt-brandtner-bikemap**
Improved update performance of transportation_name layer
- Refactored LineString-merging and diff updates in update_transportation_name.sql
- Refactored transportation_route_member_coalesced materialized view to table
- Added analyze statements before update queries during transportation_name.refresh_network and update_osm_route_member

See #1433 for more detailed discussion.

### CODE REVIEW

**Comment by TomPohys** [comment]
Great work! Could you please rebase it?

**Comment by benedikt-brandtner-bikemap** [comment]
Thanks, have pushed and rebased it

**Comment by benedikt-brandtner-bikemap** [comment]
Seens like i messed up something with the etl doc
image

I've never worked with this could you maybe give me a hint on whats wrong here?

**Comment by benedikt-brandtner-bikemap** [comment]
Thanks a lot for the tip, have regenerated the diagram and pushed it

**Review by TomPohys — APPROVED** [review]

**Pull request merged**
