### PR TITLE
Boundary - more data in zoom 7 and 8

### PR DESCRIPTION
**Pull request by eva-j**
https://github.com/openmaptiles/openmaptiles/issues/615

In many European countries is NUTS 3 administrative unit available in admin_level 6, so I updated z7 and z8 to contain data up to this level.

Styles:
* Streets, Topo, Topographique, Positron and Dark stay without change after this PR - they are displaying data from admin_level 2 - 4 only
* Basic, Bright, Hybrid, Pastel and Voyager - in zoom 7 and 8 will appear data of OSM admin_level 6

### CODE REVIEW

**Comment by nnhubbard** [comment]
Will this change make the .mbtiles file size larger?

**Comment by eva-j** [comment]
Change of tile size for boundary layer:
Czechia: 31.9 MB -> 32.5 MB
Switzerland: 14.5 MB -> 14.5 MB
India: 121.8 MB -> 138.1 MB

It requires changes in https://github.com/openmaptiles/openmaptiles-tools/blob/master/docker/import-osmborder/import_osmborder_lines.sh for `osm_border_linestring_gen6` and `osm_border_linestring_gen7` (`max_admin_level` from 4 to 6)

**Comment by eva-j** [comment]
This will wait until the generalization of boundaries is made in OMT repo.
https://github.com/openmaptiles/openmaptiles-tools/pull/123

**Comment by nyurik** [comment]
needs rebase

**Pull request merged**
