### PR TITLE
fix bug: runway & taxiway weren't extracted properly

### PR DESCRIPTION
**Pull request by lincomatic**
runway & taxi are linestrings, not polygons, so they were not being extracted properly into maps

### CODE REVIEW

**Comment by jirik** [comment]
@lincomatic Thanks for this PR. It seems there are taxiways and runways that are polygons:
https://taginfo.openstreetmap.org/tags/aeroway=runway
https://taginfo.openstreetmap.org/tags/aeroway=taxiway
http://www.openstreetmap.org/way/107298803

Therefore, could you please leave runways and taxiways also in aeroway_polygon?

It would be also good to
- order subselects in layer.sql from lowest zoom level to the highest
- change etldoc like this:
`-- etldoc:     label="layer_aeroway |<z11> z11|<z12> z12|<z13> z13|<z14_> z14+" ];`
`-- etldoc:  osm_aeroway_linestring -> layer_aeroway:z11`

**Comment by jirik** [comment]
Related to #141

**Comment by lincomatic** [comment]
jirik,
Sorry, I barely understand this stuff.. is this what you want in layer.sql?

```
-- etldoc: layer_aeroway[shape=record fillcolor=lightpink, style="rounded,filled",
-- etldoc:     label="layer_aeroway |<z12> z12|<z13> z13|<z14_> z14+" ];

CREATE OR REPLACE FUNCTION layer_aeroway(bbox geometry, zoom_level int)
RETURNS TABLE(geometry geometry, class text) AS $$
    SELECT geometry, aeroway AS class FROM (
        -- etldoc:  osm_aeroway_polygon_gen2 -> layer_aeroway:z12
        SELECT geometry, aeroway
        FROM osm_aeroway_polygon_gen2 WHERE zoom_level = 12
        UNION ALL
        -- etldoc:  osm_aeroway_polygon_gen1 -> layer_aeroway:z13
        SELECT geometry, aeroway
        FROM osm_aeroway_polygon_gen1 WHERE zoom_level = 13
        UNION ALL
        -- etldoc:  osm_aeroway_polygon -> layer_aeroway:z14_
        SELECT geometry, aeroway
        FROM osm_aeroway_polygon WHERE zoom_level >= 14
        UNION ALL
	-- etldoc: label="layer_aeroway |<z11> z11|<z12> z12|<z13> z13|<z14_> z14+" ];
        -- etldoc:  osm_aeroway_linestring -> layer_aeroway:z11_
        SELECT geometry, aeroway
        FROM osm_aeroway_linestring WHERE zoom_level >= 11
    ) AS zoom_levels
    WHERE geometry && bbox;
$$ LANGUAGE SQL IMMUTABLE;
```

**Comment by jirik** [comment]
@lincomatic I've improved in cf58a1eef663a0e0300b9368362d0bdc2dfde9a0 as I meant it and merged it as a part of [#192](https://github.com/openmaptiles/openmaptiles/pull/192/commits).
Anyway, thanks for contribution!

**Comment by lincomatic** [comment]
OK, great, thanks!

**Pull request merged**
