### PR TITLE
union ocean regular squares into complex polygon

### PR DESCRIPTION
**Pull request by TomPohys**
The ocean layer (table osm_ocean_polygon insert by `make import-data`) is made from squares that have a 10m buffer. 

This creates extra geometry in vector tiles as:
water_z8a

Union of full ocean squares should decrease the size of the water layer.

From this:
ocean_squares

to this:
ocean_union

The red squares contain the holes from the islands and coastline.

### CODE REVIEW

**Comment by TomPohys** [comment]
Partial fix #308

**Comment by nyurik** [comment]
I might be mistaken here, but I think it is done on purpose - breaking water into many polygons greatly speeds up the time needed to generate each tile because it allows much less complex polygons to be processed. Cc @Komzpa

**Comment by TomPohys** [comment]
Hi @nyurik, there are 8042 polygons (squares, 5 points, more then 100km<sup>2</sup>), which was reduced to 22 polygons - 1184kB vs 40kB respectively. 

In vector tiles should be the size reduction even more significant, due to the creation of more polygons based on a 10m buffer of each square.

**Review by daliborjanak — APPROVED** [review]

**Comment by indus** [comment]
I may be mistaken but I think this PR is the cause for some spikes in my water layer at zoom 6 (white vertical lines in the second image )
grafik
grafik

**Pull request merged**
