### PR TITLE
`transportation_name` update to consider `tags`

### PR DESCRIPTION
**Pull request by zstadler**
Following https://github.com/openmaptiles/openmaptiles/commit/8bb77b67a199746d80870fe50caca9b9c29581d6#r59190611

### CODE REVIEW

**Comment by zstadler** [comment]
@frodrigo, could you review this PR?

**Review by ZeLonewolf — APPROVED** [review]
Looks good to me, thanks for catching this missing field in the update sequence.

**Comment by TomPohys** [comment]
Thank you very much! It looks good.

**Comment by zstadler** [comment]
Thanks for accepting this PR for the next release.

**Pull request merged**
