### PR TITLE
Remove unused rank indexes in place layer

### PR DESCRIPTION
**Pull request by ZeLonewolf**
Based on analysis from planet builds for this layer as well as running updates via the integrity script as discussed in #1516, these three indexes are not used and can be removed.

### CODE REVIEW

**Comment by ZeLonewolf** [comment]
My understanding of the update scripts are that they primarily use id fields in doing updates.

**Comment by ZeLonewolf** [comment]
Also - conceptually - an index only on the rank column is pretty pointless - we're not pulling out data by queries on rank, we're pulling them out by geometry or updating by ID.

**Comment by ZeLonewolf** [comment]
Reviewing the code, I'm confident that these rank indexes aren't solving a useful purpose.  All of the queries that use rank are filtering by geometry, which would be the index used.

**Comment by benedikt-brandtner-bikemap** [comment]
Sorry was not available the past few days.

Yeah after looking at the query in more detail you are correct the index will never be since the primary-key (id) will take precedence.

Am currently also running a test-import and updates (#1516)  so maybe we could still wait until i post results from `pg_stat_all_indexes` there?

**Comment by ZeLonewolf** [comment]
Thanks, additional data would be great to ensure that I'm not missing anything.

**Comment by benedikt-brandtner-bikemap** [comment]
Have posted my results of the import and update run of a small region in the mentioned issue and you were correct these indexes have not been accessed during the update.

**Comment by TomPohys** [comment]
Thanks a lot!

**Pull request merged**
