### PR TITLE
Integrity check to generate zoom 14 tiles

### PR DESCRIPTION
**Pull request by zstadler**
Setting the MIN/MAX zoom levels in the `env` section had no effect since the values in the `.env` file have higher precedence.

See the currently effective `maxzoom = 7` value in [a typical integrity check log]( https://github.com/openmaptiles/openmaptiles/pull/1223/checks#step:3:3546).

### CODE REVIEW

**Comment by zstadler** [comment]
@TomPohys,

Please review and merge this PR so I can submit a PR for [Integrity tests to check the import-diff flow #1226](https://github.com/openmaptiles/openmaptiles/issues/1226)

**Review by TomPohys — APPROVED** [review]

**Comment by TomPohys** [comment]
Great! Thank you!

**Comment by ZeLonewolf** [comment]
Since the integrity test and performance test run in parallel, it's a no-brainer to allow the integrity test to run down to z14, since it's still shorter to run than the performance test.

**Comment by TomPohys** [comment]
Hi @ZeLonewolf, if I understand correctly (not necessary to run integrity test up to zoom 14), there is e.g. `housenumbers` layer which is only in zoom level 14. So I think it is the correct way to test integrity up to zoom level 14.

**Comment by ZeLonewolf** [comment]
@TomPohys I was saying that the new integrity test up to zoom 14 won't slow down the continuous integration :)

**Comment by TomPohys** [comment]
Ohh, OK. I am sorry for not understand it correctly :)

**Pull request merged**
