### PR TITLE
Add German names (name_de), unify English names (name_en)

### PR DESCRIPTION
**Pull request by jirik**
German names `name_de` added to layers. It contains value of the first non-empty tag:
1. `name:de`
1. `name`
1. `name:en`

Similarly, `name_en` now contains value of the first non-empty tag:
1. `name:en`
1. `name`

All layers with names were affected:
- mountain_peak
- place
- poi
- transportation_name
- water_name
- waterway

### CODE REVIEW

**Comment by jirik** [comment]
Related to #172

**Comment by nicooprat** [comment]
Hi,

Do you plan to add other languages? French would be nice :) I was using `https://osm2vectortiles.tileserver.com/v2.json` that supported it but looks like v3 doesn't...

Thanks for your work,
Regards.

**Comment by jirik** [comment]
Franch is already there, together with about 50 languages!
See https://github.com/openmaptiles/openmaptiles/releases/tag/v3.6

**Comment by nicooprat** [comment]
Ok weird my 2nd edit didn't show up. I actually found out that `{name:fr}` was available, but it gave me some disappointing results. Here are my configuration files (only `text-field` changes): https://gist.github.com/nicooprat/5679c48a89400a507c4b157c7142d371

And here are some results (in Corsica, a french Island at South of it): 
* lat: 42.13990692518783
* lng: 9.077687793814448
* zoom: 10

osm

Pretty all city names are not showing up. Any idea?

Thanks.

**Comment by jirik** [comment]
@nicooprat Because they do not have `name:fr` tag in OSM data:
https://www.openstreetmap.org/node/51305031
New `name:*` attributes are meant to be used with fallback layer. Meaning you need to create two layers:
- one for features with `name:fr` attribute (showing `name:fr` as a label)
- second for features without `name:fr` attribute (showing some other name as a label, probably `name_int`)

**Comment by nicooprat** [comment]
Ok, makes sense. I just found this: https://github.com/openmaptiles/klokantech-basic-gl-style/blob/master/lang-fallback.json but I don't understand how to implement it, any hint? Sorry if it looks obvious for you...

**Comment by jirik** [comment]
@nicooprat Sorry for delay. Nevertheles you have found it :) Another usage is here:
https://github.com/klokantech/gl-style-package-spec
I think it is not yet documented feature, but it is not difficult.

**Pull request merged**
