### PR TITLE
Map fell, heath, scrub and tundra like grassland, as 'grass'

### LINKED ISSUE #660: Scrub is not included in landcover
Scrub is currently not included in landcover.sql

I've made a fork that includes scrub to landcover/landcover.sql, landcover/mapping.yaml and landcover/landcover.yaml

### PR DESCRIPTION
**Pull request by frodrigo**
Add more natural value mapped to `grass` class.

Some empty areas are on maps because some natural kinds are not mapped. Just map this small vegetation fields to grass.

Fix #660

### CODE REVIEW

**Comment by eva-j** [comment]
Thanks for this PR.
Could you please add information about size of tiles before and after this change for some test countries?
Can you list a few places for which it make sense to include?

**Comment by frodrigo** [comment]
Alpage
https://www.openstreetmap.org/#map=13/42.9292/-0.1263
image
image

Beach
https://www.openstreetmap.org/#map=15/43.5875/-1.4826
image
image

**Comment by frodrigo** [comment]
I test on Aquitaine, France (PBF 214Mb):

* Original mbtiles size: 614.400
* With this patch : 622.592

+1.3%

sqldiff give no output. Not sure if it is normal or not.

Do you want test on larger area? but I am not sure to be able to do it.

**Comment by eva-j** [comment]
Thanks a lot for testing, it looks good, @frodrigo

**Pull request merged**
