### PR TITLE
Added OSM ref tag for aeroway layer

### PR DESCRIPTION
**Pull request by claustres**
So that for instance the runways/taxiways ID can be displayed in styles.

### CODE REVIEW

**Comment by claustres** [comment]
Example of how it is used in OSM : https://www.openstreetmap.org/#map=15/43.6319/1.3569

**Comment by jirik** [comment]
Thanks @claustres for such clean PR!

**Comment by claustres** [comment]
Thanks, will it be available in the next updates of OpenStreetMap vector tiles on OpenMaptiles.com ?

**Comment by jirik** [comment]
It will be available after next release (not update) at openmaptiles.com. The next release is planned in November.

**Comment by claustres** [comment]
We just downloaded the last version of the OSM MB tiles here https://openmaptiles.com/downloads/tileset/osm/ and the name *osm-2017-11-20-v3.6.2-planet.mbtiles* suggests it used the 3.6.2 release.

The [changelog](https://github.com/openmaptiles/openmaptiles/compare/v3.6.2...master) also suggests that this PR has been integrated. However when inspecting the tiles with TileserverGL we can't see the `ref` field, is it normal ?

Thanks for your return.

**Comment by jirik** [comment]
It will be available in 3.7 release. We are rendering and making test in these days. It should be released next week and deployed the week after, you'll find it in changelogs.

**Comment by claustres** [comment]
OK thanks

**Pull request merged**
