### PR TITLE
Paint

### PR DESCRIPTION
**Pull request by cbeddow**
Related to this issue: https://github.com/openmaptiles/openmaptiles/issues/1434

### CODE REVIEW

**Comment by cbeddow** [comment]
Removed some edits for a separate PR, which were adding parking as land use also. So this only focuses now on the paint shop POI.

**Comment by TomPohys** [comment]
A big sorry for such a delay!

**Comment by TomPohys** [comment]
Please run also `make generate devdoc` and update this PR, when there is a change in `mapping` file. Thanks

**Review by TomPohys — APPROVED** [review]

**Comment by TomPohys** [comment]
Thanks for the PR!

**Pull request merged**
