### PR TITLE
Remove workaround for quickstart.sh

### PR DESCRIPTION
**Pull request by zstadler**
Following #992

### CODE REVIEW

**Review by TomPohys — APPROVED** [review]

**Comment by TomPohys** [comment]
Test on Monaco is now up to zoom level 7. See in https://github.com/openmaptiles/openmaptiles/pull/998/checks?check_run_id=1153964282#step:3:2924

**Comment by zstadler** [comment]
@TomPohys, Please hold this PR!

**Comment by TomPohys** [comment]
Yes, we will wait, my first "approval" was a little bit premature, sorry for that.

**Comment by zstadler** [comment]
I should have tested #992 better :-(

While #992 enables overriding the values in the `.env` file by the environment when `docker-compose` is invoked, the `Makefile` overrides the values of environment variables by the values in the `.env` file ...
https://github.com/openmaptiles/openmaptiles/blob/47cdfc2c8b5c9e33711a8b8989e095ce434ba21e/Makefile#L10

**Comment by zstadler** [comment]
Test on Monaco is now up to zoom level 14.
See in https://github.com/openmaptiles/openmaptiles/pull/998/checks?check_run_id=1154403087#step:3:2900
```
-----------------  -----------------------------------------
BBOX               7.4016843,43.5165358,7.5002447,43.7543525
OSM_MAX_TIMESTAMP  2020-09-22T20:40:07Z
OSM_AREA_NAME      monaco
MIN_ZOOM           0
MAX_ZOOM           14
-----------------  -----------------------------------------
```

**Comment by zstadler** [comment]
@TomPohys I believe it is ready for merge.

**Review by TomPohys — APPROVED** [review]

**Pull request merged**
