### PR TITLE
Add requires.tables to <layer>.yaml

### PR DESCRIPTION
**Pull request by Falke-Design**
**NOTE** this can only be merged after the next tools version is released.

Added required Postgres tables to the `<layer>.yaml` definition.
Close: #1220

PR of tools: https://github.com/openmaptiles/openmaptiles-tools/pull/370

### CODE REVIEW

**Review by nyurik — COMMENTED** [review]
i think it would be cleaner to use the yaml list rather than json list - makes it easier to read.

**Comment by TomPohys** [comment]
Hi @Falke-Design, I agree that tables should be in the YAML list, the same as you did for the test in [OMT-T](https://github.com/openmaptiles/openmaptiles-tools/blob/74fcd480ecbfab63f90814c8864e7c7dbffb1965/tests/testlayers/mountain_peak/mountain_peak.yaml#L9)

Could you please update it?

Thank you

**Comment by Falke-Design** [comment]
@TomPohys should the `"` removed too? Now I changed the single items to a list too, is this ok?

**Comment by TomPohys** [comment]
Thank you, it looks better now. A single item as a YAML list looks OK, and it has consistency through all files.

If the `"` are not necessary, let`s remove them.
Thank you

**Comment by Falke-Design** [comment]
@TomPohys done

**Review by TomPohys — APPROVED** [review]

**Comment by TomPohys** [comment]
Thank you!

**Pull request merged**
