### PR TITLE
Add landuse=basin as water

### PR DESCRIPTION
**Pull request by frodrigo**
Add support of tag `landuse=basin` as water polygon.

### CODE REVIEW

**Comment by TomPohys** [comment]
Hi @frodrigo, thank you for this PR. It is very useful, but we need to know the exact increase in data volume of resulted mbtiles file. Could you please test this PR on one whole country, e.g. Switzerland, the Czech Republic or your country?

GitHub Actions do not create as accurate numbers as we wish.

Thanks

**Comment by frodrigo** [comment]
Test on Aquitaine, France, PBF 211MB.

Before
37m 14.461999999999989s
220729344 tiles.mbtiles

After
37m 10.463999999999942s
221204480 tiles.mbtiles

Size +0.21%

**Comment by TomPohys** [comment]
Hi @frodrigo, thank you for the test and this PR. Can you please update the mapping* files? I merged swimming pools (https://github.com/openmaptiles/openmaptiles/pull/878) before basin, sorry for that :-)

**Comment by frodrigo** [comment]
Rebased

**Comment by TomPohys** [comment]
Thanks

**Pull request merged**
