### PR TITLE
Fix updates on transportation_name layer

### PR DESCRIPTION
**Pull request by lazaa32**
Updates on `transporation_name` layer take much more time than before.

Tested on Switzerland - time to import a single diff (all layers), time to import/update just `transportation_name`  layer
(3.12.2 vs 3.13. vs this PR):

diff  | till data  | 3.12.2 </br> all layers| 3.13 </br> all layers | PR </br> all layers | 3.12.2 </br >transportation_name  | 3.13 </br> transportation_name   | PR </br>transportation_name
--    | --         | --                            |  --                   | --                  | --                                | --                               | --
#3399 | 2022-01-02 | 6m50.073583491s               |  13m17.812631745s     | 7m23.398765657s     | 00:00:01.893855                   | 00:07:58.861602                  | 00:00:13.561437
#3400 | 2022-01-03 | 8m4.75959592s                 |  18m25.170386374s     | 8m7.952587563s      | 00:00:01.964811                   | 00:13:14.77066                   | 00:00:33.339465
#3401 | 2022-01-04 | 9m42.808508614s               |  16m45.069075494s     | 7m58.997389623s     | 00:00:01.186381                   | 00:10:49.560629                  | 00:00:14.200444
#3402 | 2022-01-05 | 9m7.992858106s                |  27m30.221890517s     | 8m39.140444619s     | 00:00:01.469556                   | 00:19:26.266047                  | 00:00:28.535937

In 3.13 there had been introduced highway concurrency into `transportation` and `transportation_name` so I expected the update process will take more time but not that much. Because of this it's impossible to use updates on larger areas because the process takes too long.

The issue is caused by `IS NOT DISTINCT FROM` operator over `tags` (hstore) columns. I replaced it with `=` operator in combination with `coalesce()` function which returns the same results but in shorter time. Tested on https://github.com/openmaptiles/openmaptiles/blob/master/layers/transportation_name/update_transportation_name.sql#L474 and https://github.com/openmaptiles/openmaptiles/blob/master/layers/transportation_name/update_transportation_name.sql#L494 queries.

   | coalesce(n.tags, '') = coalesce(c.tags, '') | n.tags IS NOT DISTINCT FROM c.tags
-- | -- | --
DELETE | DELETE 9557</br>Time: 1437.927 ms (00:01.438) | DELETE 9557</br>Time: 278240.179 ms (04:38.240)
INSERT | INSERT 0 49685</br>Time: 11638.266 ms (00:11.638) | INSERT 0 49685</br>Time: 427126.126 ms (07:07.126)

@zstadler @ZeLonewolf could you please check this as it is related to your work? Thank you very much.

### CODE REVIEW

**Comment by zstadler** [comment]
Disclaimer: I'm not an SQL expert.

I wonder:

If indeed `coalesce(foo, "") = coalesce(bar, "")` is equivalent to `foo IS NOT DISTINCT FROM bar`, yet it has significant performance impact, why wouldn't we apply this optimization throughout the entire OpenMapTiles SQL code?

@nyurik @frodrigo @ZeLonewolf

**Comment by zstadler** [comment]
@lazaa32,

You wrote:
> |  |  	n.tags IS NOT DISTINCT FROM c.tags |	coalesce(n.tags, '') = coalesce(c.tags, '')|
> |---|---|---|
> |DELETE 	| DELETE 9557 <br/> Time: 1437.927 ms (**00:01.438**) |	DELETE 9557 <br/> Time: 278240.179 ms (**04:38.240**)|
> |INSERT |	INSERT 0 49685 <br/> Time: 11638.266 ms (**00:11.638**) |	INSERT 0 49685 <br/> Time: 427126.126 ms (**07:07.126**) |

Did you switch the column headers? 

The above table says the `IS NOT DISTINCT FROM` expression is faster than the `coalesce` expression: 
- 1.438 seconds vs 4:38.240 minutes for the delete operation
- 11.638 seconds vs. 7:07.126 minutes for the insert operation.

**Comment by lazaa32** [comment]
> @lazaa32,
> 
> You wrote:
> 
> > n.tags IS NOT DISTINCT FROM c.tags
> > coalesce(n.tags, '') = coalesce(c.tags, '')
> > 
> > 
> > 
> > 
> > DELETE
> > DELETE 9557  Time: 1437.927 ms (**00:01.438**)
> > DELETE 9557  Time: 278240.179 ms (**04:38.240**)
> > 
> > 
> > INSERT
> > INSERT 0 49685  Time: 11638.266 ms (**00:11.638**)
> > INSERT 0 49685  Time: 427126.126 ms (**07:07.126**)
> 
> Did you switch the column headers?
> 
> The above table says the `IS NOT DISTINCT FROM` expression is faster than the `coalesce` expression:
> 
> * 1.438 seconds vs 4:38.240 minutes for the delete operation
> * 11.638 seconds vs. 7:07.126 minutes for the insert operation.

Sorry, my bad, I really did swap the column headers. Fixed now.

**Comment by zstadler** [comment]
> Sorry, my bad, I really did swap the column headers. Fixed now.
@lazaa32, I've deleted my comment. Please feel free to delete your reply.

This message will be deleted within 24 hours...

**Comment by lazaa32** [comment]
> Disclaimer: I'm not an SQL expert.
> 
> I wonder:
> 
> If indeed `coalesce(foo, "") = coalesce(bar, "")` is equivalent to `foo IS NOT DISTINCT FROM bar`, yet it has significant performance impact, why wouldn't we apply this optimization throughout the entire OpenMapTiles SQL code?
> 
> @nyurik @frodrigo @ZeLonewolf

Not an SQL expert either.
But it seems that there is a significant performance impact only when `foo` and `bar` are of `hstore` column type.

**Review by TomPohys — APPROVED** [review]

**Comment by TomPohys** [comment]
Thanks a lot!

**Comment by frodrigo** [comment]
There is an index for that
```sql
CREATE INDEX IF NOT EXISTS osm_transportation_name_linestring_name_ref_idx ON osm_transportation_name_linestring (coalesce(tags->'name', ''), coalesce(ref, ''));
```

The changes of this PR will not use the index, not sure why is it faster.
But I guess the index have to be changed to
```diff
-CREATE INDEX IF NOT EXISTS osm_transportation_name_linestring_name_ref_idx ON osm_transportation_name_linestring (coalesce(tags->'name', ''), coalesce(ref, ''));
+CREATE INDEX IF NOT EXISTS osm_transportation_name_linestring_name_ref_idx ON osm_transportation_name_linestring (coalesce(tags, ''), coalesce(ref, ''));
```

or the clause
```diff
-AND coalesce(n.tags, '') = coalesce(c.tags, '')
+AND coalesce(n.tags->'name', '') = coalesce(c.tags, '')
+AND n.tags IS NOT DISTINCT FROM c.tags --like before
```

**Pull request merged**
